from langchain.document_loaders import TextLoader
from langchain.document_loaders import PYPDFLoader
from langchain.text_splitters import RecursiveCharacterTextSplitter
from langchain.text_splitters import CharacterTextSplitter
from langchain.vectorstores import DocArrayInMemorySearch
from langchain.vectorstores.retriever import Retriever
from langchain.memory import ConversationBufferMemory
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.chat_model import ChatOpenAI
from langchain.chains import RetrievalQA, ConversationalRetrievalChain
